version: '3.8'

services:
  openllm-chat:
    build: .
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_BASE_URL=http://host.docker.internal:3000